name: Reusable Greeting Workflow

on:
  workflow_call:
    inputs:
      person_name:
        description: "Name of the person"
        required: true
        type: string
      environment:
        type: string
        required: true  # name of GH environment (dev/test/prod)
        
jobs:
  greet:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, ${{ inputs.person_name }}!"
